name: 🐛 Bug Report
description: Report a bug to help us improve NEETAI
title: "[BUG] "
labels: ["bug", "triage"]
assignees: 
  - chakravartyharish

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this bug! 🐛
        
        Please fill out this template with as much detail as possible to help us understand and reproduce the issue.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting a bug report
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I have reproduced this issue with the latest version of the application
          required: true
        - label: I have checked the documentation and this is not expected behavior
          required: true

  - type: textarea
    id: description
    attributes:
      label: 🔍 Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what went wrong...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      value: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain your problem
      placeholder: Drag and drop images/videos here, or paste URLs

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Severity Level
      description: How severe is this bug?
      options:
        - Critical (Application crashes, data loss, security issue)
        - High (Major feature broken, blocks workflow)
        - Medium (Feature partially broken, workaround exists)
        - Low (Minor issue, cosmetic problem)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: 🎯 Affected Component
      description: Which part of the application is affected?
      options:
        - Web App - Authentication
        - Web App - Dashboard
        - Web App - Quiz/Questions
        - Web App - AI Features
        - Web App - Profile/Settings
        - Mobile App - Authentication
        - Mobile App - Quiz/Questions
        - Mobile App - AI Features
        - API/Backend
        - Database
        - CI/CD Pipeline
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: 🌐 URL (if applicable)
      description: The URL where the bug occurred
      placeholder: https://neetai.vercel.app/...

  - type: textarea
    id: browser-info
    attributes:
      label: 🌐 Browser Information
      description: If this is a web-related bug, provide browser details
      placeholder: |
        - Browser: Chrome
        - Version: 118.0.0.0
        - OS: Windows 11
      value: |
        - Browser: 
        - Version: 
        - OS: 

  - type: textarea
    id: device-info
    attributes:
      label: 📱 Device Information (Mobile bugs)
      description: If this is a mobile bug, provide device details
      placeholder: |
        - Device: iPhone 14
        - OS: iOS 16.5
        - App Version: 1.0.0
      value: |
        - Device: 
        - OS: 
        - App Version: 

  - type: textarea
    id: console-logs
    attributes:
      label: 🔧 Console Logs/Error Messages
      description: Any relevant error messages or console logs
      placeholder: Paste console logs, error messages, or stack traces here
      render: bash

  - type: textarea
    id: network
    attributes:
      label: 🌐 Network Information
      description: Any network-related information that might be relevant
      placeholder: |
        - Connection: WiFi/Mobile
        - Speed: Fast/Slow
        - Any proxy/VPN in use?

  - type: textarea
    id: additional-context
    attributes:
      label: 📝 Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Does this happen consistently or intermittently?
        - Are there any workarounds?
        - When did this start happening?
        - Any recent changes to your setup?

  - type: checkboxes
    id: volunteer
    attributes:
      label: 🤝 Contribution
      description: Would you be willing to help fix this bug?
      options:
        - label: I would be willing to submit a pull request to fix this issue
          required: false